version: '3.4'

services:
  gateway:
    depends_on: [identity]
    image: gateway:latest
    container_name: gateway
    restart: always
    build:
      context: src/ApiGateways

  identity:
    image: identity:latest
    container_name: identity
    restart: always
    build:
      context: src/Services/Identity