version: '3.4'

services:

  rabbit-mq:
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672

  sql-data:
    environment:
      SA_PASSWORD: "Password_111ssassSsvc111"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports: 
        - 14330:1433

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=hello
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - FILE_SAVING_PATH=/files
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.aspnet/files:/app/files:rw

  heritage-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=hello
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - FILE_SAVING_PATH=/objects
    volumes:
      -  ~/.aspnet/https:/https:ro
      -  ~/.aspnet/objects:/app/objects:rw
  
  fileservice-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=hello
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - FILE_SAVING_PATH=/files
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.aspnet/files:/app/files:rw

  logger-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FILE_SAVING_PATH=/logger
    volumes:
      -  ~/.aspnet/logger:/logger:rw

  ocelot-api-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=hello
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ~/.aspnet/https:/https:ro