version: '3.4'

services:
  gateway:
    depends_on: [identity, heritage]
    image: gateway:latest
    container_name: gateway
    restart: always
    build:
      context: src/ApiGateways

  identity:
    image: identity:latest
    container_name: identity
    restart: always
    build:
      context: src/Services/Identity

  dbContainer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: dbContainer
    restart: always
        
  heritage:
    image: heritage:latest
    container_name: heritage
    restart: always
    build:
      context: src/Services/Heritage