version: '3.4'

services:

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    restart: always
    
  sql-data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-data
    restart: always

  identity-api:
    image: identity:latest
    container_name: identity-api
    restart: always
    build:
      context: src/Services/Identity
#    depends_on:
#      - sql-data
#      - rabbit-mq         

  heritage-api:
    image: heritage:latest
    container_name: heritage-api
    restart: always
    build:
      context: src/Services/Heritage
#    depends_on:
#      - sql-data
#      - rabbit-mq
      
  logger-api:
    image: logger:latest
    container_name: logger-api
    restart: always
    build:
      context: src/Services/Logger
#    depends_on:
#      - rabbit-mq

  ocelot-api-gateway:
    image: ocelot-api-gateway:latest
    container_name: ocelot-api-gateway
    restart: always
    build:
      context: src/ApiGateways
#    depends_on:
#      - rabbit-mq
#      - sql-data
#      - identity-api
#      - heritage-api
#      - logger-api